# Generated by Django 2.0.6 on 2018-06-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='record',
        ),
        migrations.AddField(
            model_name='fighter',
            name='draws',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='losses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
