# Generated by Django 2.0.6 on 2018-09-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0003_fighter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='image',
        ),
    ]
