# Generated by Django 2.0.6 on 2018-09-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0004_remove_fighter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
